# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rackctl < Formula
  desc "The day-0 installer for a nanohype platform"
  homepage "https://rackctl.com"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rackctl/rackctl/releases/download/v0.1.0/rackctl_darwin_amd64.tar.gz"
      sha256 "f613fe1d35c9191c2cf0d51e826f3575b6ea8440fc12556daed55f99c0b59b75"

      define_method(:install) do
        bin.install "rackctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rackctl/rackctl/releases/download/v0.1.0/rackctl_darwin_arm64.tar.gz"
      sha256 "e6845accd54263bc1f50538185b4de348a820ee7e7f9e9b712776c4d856fc16e"

      define_method(:install) do
        bin.install "rackctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rackctl/rackctl/releases/download/v0.1.0/rackctl_linux_amd64.tar.gz"
      sha256 "f513bae0c819884da42b39ff474461200ab6ee104a5408708c49c16b4aa5b213"
      define_method(:install) do
        bin.install "rackctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rackctl/rackctl/releases/download/v0.1.0/rackctl_linux_arm64.tar.gz"
      sha256 "44fc1dc8556b14ebce3d9d64d7204bea8d6b79b56ddac1dea612fc994f578768"
      define_method(:install) do
        bin.install "rackctl"
      end
    end
  end
end
