# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rackctl < Formula
  desc "The day-0 installer for a nanohype platform"
  homepage "https://rackctl.sh"
  version "0.4.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rackctl/rackctl/releases/download/v0.4.0/rackctl_darwin_amd64.tar.gz"
      sha256 "c04121983f0a2002cdf06c77b39c6b863d583de622eb231326ccd1eccaf6a53e"

      define_method(:install) do
        bin.install "rackctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rackctl/rackctl/releases/download/v0.4.0/rackctl_darwin_arm64.tar.gz"
      sha256 "155ace60472970249f9f6456c7529431fb8cbd09b8ce584fe8427a4626e8080b"

      define_method(:install) do
        bin.install "rackctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rackctl/rackctl/releases/download/v0.4.0/rackctl_linux_amd64.tar.gz"
      sha256 "4db03c5b50f0895728d98becf0d617824a7e277a37cef36df907e75fca20a4c4"
      define_method(:install) do
        bin.install "rackctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rackctl/rackctl/releases/download/v0.4.0/rackctl_linux_arm64.tar.gz"
      sha256 "5000f5eb2adad3bdec5da8063e93695e2d4efb2db24405aed7c5d2a96d395890"
      define_method(:install) do
        bin.install "rackctl"
      end
    end
  end
end
